---
title: Mapping landscape suitability for forest thinning to reduce evapotranspiration and enhance groundwater recharge in Arizona
format:
#    docx: default
    elsevier-pdf:
        keep-tex: true
    elsevier-html: default

author:
  - name: Ryan E Lima 
    orcid: 0000-0002-5352-7215
    corresponding: true
    email: ryan.lima@nau.edu
    roles:
      - conceptualization
      - Investigation
      - Formal analysis
      - Writing – original draft
    affiliations: 
      - Northern Arizona University
  - name: Neha Gupta
    orcid: 0000-0002-2247-3509
    corresponding: false
    roles:
    - Writing – review and editing
    - Project administration
    affiliations:
      - University of Arizona
  - name: Travis Zalesky
    orcid: 0009-0006-0181-3099
    corresponding: false
    roles:
      - software
      - data curation
      - visualization
    affiliations:
      - University of Arizona
  - name:  Temuulen Tsagaan Sankey
    orcid: 0000-0002-7859-8394
    corresponding: false
    roles:
    - Writing – review and editing
    - Project administration
    affiliations:
      - Northern Arizona University
  - name: Abraham E Springer
    orcid: ????
    corresponding: false
    roles:
    - Writing – review and editing
    - Project administration
    affiliations:
      - Northern Arizona University
  - name: Katherine Jacobs
    orcid: ????
    corresponding: false
    roles:
      - Project administration
      - Editing
    affiliations:
      - University of Arizona
      
keywords:
  - suitability mapping
  - Forest thinning
  - Water yield
  - groundwater recharge
  - GIS-MCDM
  - AHP

abstract: 
    Literature on the relationship between forest thinning and water yield was used to develop suitability criteria to map where forest treatment is most likely to enhance groundwater recharge across the Coconino National Forest in Arizona. Rechage in the region is ephemeral and focused in periods of snowmelt and locations of enhanced permeability when soil moisture exceeds threshold levels. Our approach combines thematic maps of criteria such as average precipitation, snow dominance, slope, aspect,landscape morphology, forest density, lithology and hydrologic soil type into a GIS-Multi-Criteria Decision Making model. Pairwise comparisons were made between criteria, and Analytic Hierachy Process was used as a weighting method. 
    
key-points:
  - Produced suitability map of where forest thinning may reduce evaporative demand increasing water available for streamflow and recharge throughout the State of Arizona
  - Rainfall runoff modeling would compliment this work
bibliography: bibliography.bib
csl: elsarticle.csl
citation:
  container-title: Journal of Environmental Management
keep-tex: true
funding: Arizona Board of Regents
date: last-modified
number-sections: true
---

# Introduction

Warming associated with anthropocentric climate change has increased the number of extreme hydroclimate events in the Colorado River Basin. Droughts, heatwaves, and floods have more than doubled in frequency since 2010 [@bennett_concurrent_2021].Since 2000, the Colorado River Basin has been in the midst of a historic drought [@meko_treering_2022; @williams_rapid_2022]. During that time, streamflow in the Colorado River has declined by 19% relative to the 1906-1999 average [@hogan_recent_2024; @udall_twentyfirst_2017].Rapid population growth in the Southwest and Arizona, in particular, is increasing the demands on already strained water supplies in the State. Reductions in streamflow have increased reliance on groundwater pumping, while groundwater levels have declined for decades in many groundwater basins across Arizona [@tadych_historical_2024].

Concurrently, the risk of catastrophic wildfires is increasing in Western forests--an emerging driver of runoff change that will increase the impact on the water supply [@williams_rapid_2022]. Forest structure in the forests of Northern Arizona and New Mexico has changed significantly post-Euro-American settlement. Many forests are overstocked relative to pre-settlement conditions due to grazing, logging, and wildfire exclusion [@covington_southwestern_1994; @friederici2013]. These changes have increasing the risk of catastrophic wildfire [@allen_ecological_2002]. Rising temperatures and related droughts have contributed to extensive tree mortality from wildfire, disease, and insect infestation [@berner_tree_2017]. Warming temperatures have tripled the frequency and quadrupled the size of wildfires since 2000 \[[@iglesias2022]\].

Landscape-scale forest restoration efforts have been planned or implemented across much of Arizona. For example, the Four Forest Restoration Initiative (4FRI) includes plans for restoration across over 1 million hectares of Arizona's forests [@schultz_collaborative_2012]. The primary goal of restoration efforts is to reduce wildfire risk [@allen_ecological_2002; @friederici2013]. However, numerous studies have linked forest treatments to increased water yields in semi-arid forests and have emphasized the role of forest restoration in improving hydrologic services and increasing water availability [@bosch_review_1982; @baker_effects_1986; @gottfried_moderate_1991; @smerdon_overview_2009; @zou_streamflow_2010; @wyatt_estimating_2013; @moreno_modeling_2015; @simonit_impact_2015; @wyatt_semiarid_2015; @odonnell_forest_2018; @schenk_impacts_2020; @hibbert1979].

While the connection between forest treatment and water yield is well documented, the response of forests to treatments is complex and non-linear and differs across forest types, with treatment level, and along aspect and elevational gradients [@del_campo_global_2022; @biederman_streamflow_2022; @zou_streamflow_2010; @hibbert1979; @moore_physical_2005]. Regardless of the potential for increased water yield the enhancement of groundwater recharge rarely, if ever, ranks among the primary motivations for forest treatment even among projects with the stated goal of improving watershed health [@stanturf2014; @filoso2017; @allen_ecological_2002; @friederici2013; @odonnell2016]. This study examines forest restoration through the lens of groundwater recharge enhancement and identifying potential recharge zones. All else held equal, we map suitability for forest thinning with the goal of enhancing recharge. Suitability maps like these may complement (or supplement) existing frameworks for prioritizing landscape-scale forest management.

Suitability mapping, and particularly GIS-based Multi-criteria decision making (GIS-MCDM), is widely used to map potential recharge zones and areas suitable for Managed Aquifer Recharge (MAR), but to our knowledge, it has not yet been implemented to map recharge enhancement potential through forest thinning [@fathi2021; @rajashekar2023]. Pairwise comparisons were made between criteria including average precipitation, snow dominance, slope, aspect, landscape morphology, forest density, lithology, and hydrologic soil type, and the Analytic Hierarchy Process (AHP) was used as a weighting method.

------------------------------------------------------------------------

Forest treatments such as thinning and burning can significantly impact the hydrologic cycle of forests [@del_campo_global_2022]. For example, forest thinning in Arizona has been associated with increased snow cover days [@sankey_multi-scale_2015; @belmonte_uav-based_2021; @donager_integrating_2021], greater soil moisture [@belmonte_soil_2022; @sankey_thinning_2022], and greater forest canopy moisture [@sankey_regionalscale_2021]. However, the response of forests to treatments is complex and non-linear and differs across forest types, with treatment level, and along aspect and elevational gradients [@del_campo_global_2022; @biederman_streamflow_2022; @zou_streamflow_2010; @hibbert1979; @moore_physical_2005].

Water yield can decrease with reductions in forest cover in drier forests with little topographic shading or SW aspects due to increased water use by remaining vegetation and increased snow sublimation or direct evaporation of soil moisture [@biederman_recent_2015; @goeking_forests_2020]. Biederman and others [@biederman_streamflow_2022] found that low-elevation forests in Arizona may produce less streamflow following reductions in canopy cover due to wildfire, highlighting the importance of elevation and particularly water-energy asynchrony to water yield [@webb2024]. The effects of forest treatment appear to have little or no effect on water yield in areas receiving less than 500mm of annual precipitation [@biederman_streamflow_2022; @carroll_evaluating_2016; @adams_ecohydrological_2012; @zou_streamflow_2010; @hibbert1979].

## Literature Reviewed

## Study Area

Coconino National forest is 812605 Ha

Ponderosa Pine covers 336,046 Ha of the Coconino = 41.35%

## Acknowledgments

Phasellus interdum tincidunt ex, a euismod massa pulvinar at. Ut fringilla ut nisi nec volutpat. Morbi imperdiet congue tincidunt. Vivamus eget rutrum purus. Etiam et pretium justo. Donec et egestas sem. Donec molestie ex sit amet viverra egestas. Nullam justo nulla, fringilla at iaculis in, posuere non mauris. Ut eget imperdiet elit.

## Open research

Phasellus interdum tincidunt ex, a euismod massa pulvinar at. Ut fringilla ut nisi nec volutpat. Morbi imperdiet congue tincidunt. Vivamus eget rutrum purus. Etiam et pretium justo. Donec et egestas sem. Donec molestie ex sit amet viverra egestas. Nullam justo nulla, fringilla at iaculis in, posuere non mauris. Ut eget imperdiet elit.

## References {.unnumbered}

::: {#refs}
:::
